version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        and:
          - must_exclude:
              regex: 'work in progress'
              message: 'work in progress must be excluded'
